In [1]:
import torch

In [2]:
x = torch.empty(3,4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[-8.6210e-34,  4.5874e-41,  4.6323e-14,  3.3083e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  7.9234e+34,  2.7340e+20,  6.8589e+22]])


In [3]:
zeros = torch.zeros(2,3)
print(zeros)

ones = torch.ones(4,6)
print(ones)

torch.manual_seed(34514)
random = torch.rand(5,3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
tensor([[0.2665, 0.8317, 0.5322],
        [0.5536, 0.4042, 0.4845],
        [0.2333, 0.3251, 0.6874],
        [0.8986, 0.3120, 0.6212],
        [0.1603, 0.3260, 0.8760]])


In [5]:
x = torch.empty(1, 3, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([1, 3, 3])
tensor([[[-8.6209e-34,  4.5874e-41,  4.7273e-14],
         [ 3.3083e-41,         nan,  0.0000e+00],
         [ 4.8222e+30,  1.8057e+28,  7.9050e+31]]])
torch.Size([1, 3, 3])
tensor([[[-1.1800e+26,  3.3087e-41,  0.0000e+00],
         [ 0.0000e+00,  1.4013e-45,  0.0000e+00],
         [ 0.0000e+00,  8.3994e-13,  1.1210e-43]]])
torch.Size([1, 3, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([1, 3, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([1, 3, 3])
tensor([[[0.5443, 0.7321, 0.0169],
         [0.1441, 0.1688, 0.2516],
         [0.0249, 0.5759, 0.9650]]])


In [6]:
some_constants = torch.tensor([[6.2246, 7.2543], [9.52131,6.12421]])
print(type(some_constants))
print(some_constants)

some_integers = torch.tensor((5,7,2,55,98,3,2,75,32,6,2,9,21,76,0))
print(type(some_integers))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(type(more_integers))
print(more_integers)

<class 'torch.Tensor'>
tensor([[6.2246, 7.2543],
        [9.5213, 6.1242]])
<class 'torch.Tensor'>
tensor([ 5,  7,  2, 55, 98,  3,  2, 75, 32,  6,  2,  9, 21, 76,  0])
<class 'torch.Tensor'>
tensor([[2, 4, 6],
        [3, 6, 9]])


In [8]:
a = torch.ones((1, 3), dtype=torch.int16)
print(a)

b = torch.rand((4, 4), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1]], dtype=torch.int16)
tensor([[12.5880,  4.1721,  4.9548,  3.9444],
        [ 6.0055,  4.5935, 15.5374, 14.1687],
        [12.3699,  5.1719,  8.6020,  2.7520],
        [16.6135,  6.7920, 14.5003, 10.9540]], dtype=torch.float64)
tensor([[12,  4,  4,  3],
        [ 6,  4, 15, 14],
        [12,  5,  8,  2],
        [16,  6, 14, 10]], dtype=torch.int32)


In [13]:
d = torch.ones((1, 3), dtype=torch.bool)
print(d)

e = torch.rand((4, 4), dtype=torch.double)
print(e)

tensor([[True, True, True]])
tensor([[0.9643, 0.7247, 0.3136, 0.6244],
        [0.5707, 0.0262, 0.1718, 0.3114],
        [0.8452, 0.2137, 0.9704, 0.2414],
        [0.3738, 0.9287, 0.4931, 0.0417]], dtype=torch.float64)


In [15]:
# Create a tensor on CPU
cpu_tensor = torch.tensor([1, 2, 3])

# Check if the tensor is on CUDA (GPU)
is_cuda = cpu_tensor.is_cuda
print(is_cuda)  # Output: False

False


In [17]:

# Create a tensor on CPU
cpu_tensor = torch.tensor([1, 2, 3])
print(cpu_tensor.device)  # Output: cpu


cpu


In [18]:
import torch

# Create a 2D tensor
original_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Transpose the tensor
transposed_tensor = original_tensor.T

print("Original Tensor:")
print(original_tensor)
print("Transposed Tensor:")
print(transposed_tensor)


Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Transposed Tensor:
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [20]:
# Create a 2D tensor
original_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Transpose the tensor
transposed_and_conjugated_tensor = original_tensor.H

print("Original Tensor:")
print(original_tensor)
print("Transposed and Conjugated Tensor:")
print(transposed_and_conjugated_tensor)

Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Transposed and Conjugated Tensor:
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [22]:
# Create a regular tensor
x = torch.tensor([1, 2, 3])

# Check if it's a meta tensor (should be False)
print(x.is_meta)  # Output: False


False


In [23]:
# Create a tensor and perform some operations
x = torch.tensor([2.0], requires_grad=True)
y = x**2 + 3*x + 1

# Perform backward pass to compute gradients
y.backward()

# Access the gradient of the tensor with respect to the scalar value
gradient = x.grad # after differenciation 2x+3 = 2(2.0)+3 = 7
print(gradient)

tensor([7.])


In [25]:
# Create a tensor
original_tensor = torch.tensor([1, 2, 3])

# Clone the tensor
cloned_tensor = original_tensor.clone()
print(cloned_tensor)

tensor([1, 2, 3])


In [28]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Sum along dimension 0 (columns)
sum_along_dim0 = tensor.sum(dim=0)
print(sum_along_dim0)


# Sum along dimension 1 (rows)
sum_along_dim1 = tensor.sum(dim=1)
print(sum_along_dim1)

tensor([5, 7, 9])
tensor([ 6, 15])


In [33]:
# Sample data
data = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate correlation coefficients (between rows)
corr_matrix = torch.corrcoef(data)
print(corr_matrix)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [35]:
# Sample tensor
tensor = torch.tensor([[1, 0, 3], [0, 4, 0], [0,0,0], [0,3,5], [4,8,2]])

# Count non-zero elements across all dimensions
non_zero_count = tensor.count_nonzero()
print(non_zero_count)

# Count non-zero elements along the first dimension (rows)
non_zero_count_rows = tensor.count_nonzero(dim=0)
print(non_zero_count_rows)

tensor(8)
tensor([2, 3, 3])


In [36]:
# Sample matrix
matrix = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extract diagonal elements
diagonal = torch.diag(matrix)
print(diagonal)

tensor([1, 5, 9])


In [43]:

# Sample tensors
matrix2 = torch.tensor([[1, 2], [3, 4]])
matrix1 = torch.tensor([[5, 6], [7, 8]])

# Matrix multiplication
result = torch.dot(matrix1,matrix2)
print(result)

TypeError: dot() missing 1 required positional arguments: "tensor"

In [44]:
# Sample tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reshape to a row vector (view)
reshaped_tensor = tensor.reshape(-1)  # Equivalent to tensor.reshape(6)
print(reshaped_tensor)  # Output: tensor([1, 2, 3, 4, 5, 6])

tensor([1, 2, 3, 4, 5, 6])


In [45]:
tensor = torch.tensor([2, 1, 2, 3, 1, 4])

# Get unique elements (sorted)
unique_elements = tensor.unique()
print(unique_elements)

tensor([1, 2, 3, 4])
