In [3]:
import torch

In [5]:
# Create a matrix of (3,4,5)
ten =  torch.ones(3,4,5, dtype=torch.float)
print(ten)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


In [8]:
# creating a 4 by 5 tensor with random integers in between 5 and 30
int_ten = torch.randint(5,30,(4,5))
print(int_ten)

tensor([[22,  8, 14, 10, 11],
        [13, 26, 12, 11, 23],
        [26, 28,  6, 12,  6],
        [ 6, 24, 27,  6, 21]])


In [10]:
# Create a tensor with all 5s, with the shape (3,3)

t1 = torch.randint(5,6,(3,3))
print(t1)

# create a tesnsor with all n walue with shape p*q
# ten = torxh.randint(n,n+1, (p,q))

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [11]:
# finding no of elemensts in Tensor
print(torch.numel(t1))

9


In [10]:
t2 = torch.ones(3,6, dtype=torch.float)
print(t2)

In [11]:
# same shape like t2 but with different values and data types
t2_like = torch.randn_like(t2, dtype=torch.float)
print(t2_like)


tensor([[-1.5945, -1.6779,  2.3649,  0.5030,  0.7337,  0.6632],
        [-0.1112, -1.2166,  0.1402, -2.0070,  1.5269,  1.2455],
        [-1.3656,  0.7048, -0.8172, -1.4511, -0.4125, -0.6136]])


In [12]:
# Add two Tensors
sum = torch.add(t2,t2_like)
print(sum)

# to perform this data type should compatible and size should be the same

tensor([[-0.5945, -0.6779,  3.3649,  1.5030,  1.7337,  1.6632],
        [ 0.8888, -0.2166,  1.1402, -1.0070,  2.5269,  2.2455],
        [-0.3656,  1.7048,  0.1828, -0.4511,  0.5875,  0.3864]])


In [13]:
# alternate approach

#t2 <- t2+t2_like

t2 = t2.add_(t2_like)

In [14]:
print(t2)

tensor([[-0.5945, -0.6779,  3.3649,  1.5030,  1.7337,  1.6632],
        [ 0.8888, -0.2166,  1.1402, -1.0070,  2.5269,  2.2455],
        [-0.3656,  1.7048,  0.1828, -0.4511,  0.5875,  0.3864]])


### Tensor Slicing

In [16]:
# tensor[row_range, column_range]

print(t2)
t2.shape


t2[:,0:2]

tensor([[-0.5945, -0.6779,  3.3649,  1.5030,  1.7337,  1.6632],
        [ 0.8888, -0.2166,  1.1402, -1.0070,  2.5269,  2.2455],
        [-0.3656,  1.7048,  0.1828, -0.4511,  0.5875,  0.3864]])


tensor([[-0.5945, -0.6779],
        [ 0.8888, -0.2166],
        [-0.3656,  1.7048]])