In [1]:
import torch

In [2]:
torch.__version__

'2.3.0+cu121'

In [3]:
!pip show torch

Name: torch
Version: 2.3.0+cu121
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /usr/local/lib/python3.10/dist-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: fastai, torchaudio, torchtext, torchvision


In [4]:
torch.cuda.is_available()

True

In [5]:
# Tensors - GPU Data Strcuture

num = [1,2,3,4,5]


tensor1 = torch.tensor(num)
print(tensor1)

tensor([1, 2, 3, 4, 5])


In [7]:
tensor2d = torch.tensor([[1,2,3,4],[5,6,7,8]])
print(tensor2d)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [8]:
ten = torch.tensor([[1,2,3,4],[5,6,7,8]],dtype= torch.float, requires_grad=True)
print(ten)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], requires_grad=True)


In [9]:
print(ten.grad)

None


In [10]:
ten.shape

torch.Size([2, 4])

In [11]:
ten.shape[0]

2

In [12]:
ten.shape[1]

4

In [14]:
y = torch.ones((2,4))
print(y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [15]:
ft = torch.FloatTensor([[1,2,3,4,5],[6,7,8,9,10]])
print(ft)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])


In [16]:
dt = torch.DoubleTensor([[1,2,3,4],[5,6,7,8]])
print(dt)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], dtype=torch.float64)


In [17]:
# Reshaping

ft = torch.tensor([[1,2,3,4,5],[6,7,8,9,10]])
ft.shape

torch.Size([2, 5])

In [18]:
ft.view(10)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
ft.view(5,2)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [21]:
t1 = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
t1

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [22]:
t1.shape

torch.Size([4, 3])

In [26]:
t1.view(2,-1) #(row,columns)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [27]:
t1.view(-1,12)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [30]:
t2=torch.zeros(5,5)
t2

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [31]:
# 3D Tensor

# (chanels, rows, columns)

tf3 = torch.ones([3,4,5])
tf3

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [33]:
ten3d = torch.rand(3,4,5)
ten3d

tensor([[[0.1147, 0.6687, 0.9667, 0.9290, 0.2755],
         [0.8122, 0.6158, 0.7346, 0.2752, 0.1126],
         [0.4294, 0.2595, 0.5913, 0.9545, 0.5067],
         [0.4368, 0.1676, 0.3525, 0.7720, 0.2193]],

        [[0.5366, 0.4918, 0.7529, 0.8460, 0.3481],
         [0.1829, 0.9269, 0.0236, 0.4757, 0.1913],
         [0.4258, 0.8737, 0.0863, 0.7145, 0.8891],
         [0.0139, 0.8878, 0.4014, 0.0552, 0.8283]],

        [[0.6821, 0.7516, 0.6360, 0.9656, 0.3940],
         [0.3002, 0.8697, 0.8599, 0.4366, 0.4894],
         [0.5573, 0.4561, 0.6849, 0.6369, 0.5422],
         [0.6360, 0.8651, 0.7852, 0.7893, 0.3755]]])

In [37]:
tend3d1 = torch.randn(3,4,5)
tend3d1

tensor([[[-0.6527,  1.4060,  0.1894,  0.9186,  0.6481],
         [ 1.0777,  0.3452, -0.6686,  0.1113,  0.2209],
         [-1.2657,  0.6110,  2.0581, -0.1680, -1.9253],
         [ 1.8820, -0.8147,  0.3946,  1.0184,  1.2093]],

        [[ 0.3838,  0.2750, -0.0579, -1.4849,  0.8580],
         [-0.0782,  1.4850,  1.0364, -1.0491, -1.3489],
         [-0.4424,  1.0119,  0.3871, -0.7592, -1.6026],
         [ 1.3162, -0.6513, -0.9750, -0.1508,  0.4054]],

        [[ 0.3595, -0.7643,  0.3042, -0.7477,  0.9353],
         [-1.7688,  0.4766, -2.4109, -0.6306,  0.1523],
         [-1.3320, -0.9645,  1.6106, -1.0865,  0.7303],
         [-0.0837, -1.4029,  1.9817, -0.1458, -0.2149]]])